<a href="https://colab.research.google.com/github/Chanakarn06/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Numpy Array**

สร้าง Numpy Array

In [2]:
np_a = np.array([[1,2,3],[4,5,6]])  #สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]])

In [6]:
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

# matrix transpose

In [7]:
np_z = np.zeros((4,5))

In [8]:
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

**สร้าง matrix random**

In [11]:
np_random = np.random.randn(5,5)
np_random

array([[-0.49982786, -1.27692789,  0.03999506,  1.0509269 , -1.15570315],
       [ 1.39978936,  0.8442863 ,  0.24496762,  0.11929537,  0.23723886],
       [ 0.37597037, -1.07479145,  1.1957935 ,  0.06210243,  1.13026759],
       [-0.19470272, -0.02863042, -1.00909437, -0.51240747,  0.95275569],
       [-0.61168746,  1.3645538 ,  0.2915837 ,  1.20557877,  0.64899874]])

In [12]:
2 + (5*np.random.randn(3,3))

array([[ -1.12720955,   4.75588649,   1.78216523],
       [  8.54677749,   4.01876668, -15.84559678],
       [ -0.05374245,   8.4849711 ,  -1.95757378]])

random(int)

In [13]:
np.random.randint(5,11,(4,5))

array([[ 9,  9,  9,  7,  5],
       [ 9,  8,  7,  8,  6],
       [ 7,  8,  6, 10,  6],
       [ 8, 10, 10, 10,  7]])