<a href="https://colab.research.google.com/github/Chanakarn06/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Numpy Array**

สร้าง Numpy Array

In [2]:
np_a = np.array([[1,2,3],[4,5,6]])  #สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]])

In [6]:
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

# matrix transpose

In [7]:
np_z = np.zeros((4,5))

In [8]:
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

**สร้าง matrix random**

In [11]:
np_random = np.random.randn(5,5)
np_random

array([[-0.08202262,  0.4076859 , -0.03468612,  0.32260989, -0.59278811],
       [ 0.06239181, -0.12780048,  1.01782543, -0.11389537,  1.31552667],
       [-0.23706764, -0.45787609,  0.3222077 , -0.44992144,  0.9838575 ],
       [-2.58094666, -0.40830724,  0.48350939,  2.57748765,  0.13783532],
       [-1.60467387,  0.68776629, -0.20560874,  0.36922123,  0.62204001]])

In [12]:
2 + (5*np.random.randn(3,3))

array([[ 0.71497134,  4.47334683,  5.17527874],
       [ 5.93800358, -2.80556124,  2.12583398],
       [ 1.05974817,  9.45135053,  0.63094785]])

random(int)

In [13]:
np.random.randint(5,11,(4,5))

array([[10,  5,  8,  7,  6],
       [ 8,  6,  7,  9,  9],
       [ 9,  8,  8,  7,  8],
       [ 8,  8,  5,  7,  9]])

# matrix properties

In [14]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np_a.T #transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
1+ np_a

array([[2, 3, 4],
       [5, 6, 7]])

In [18]:
2*np_a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [20]:
np_c = np.array([[6,5,4],[3,2,1]])
np_c

array([[6, 5, 4],
       [3, 2, 1]])

In [21]:
np_a + np_c #adding matrix to matrix

array([[7, 7, 7],
       [7, 7, 7]])

In [22]:
np_a.shape

(2, 3)

In [23]:
np_c.shape

(2, 3)

In [25]:
np.dot(np_a,np_c.T)

array([[28, 10],
       [73, 28]])

Index

In [26]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np_a[1,1] #ชี้เลขต้องการ

5

In [28]:
np_a[1,2]

6

In [30]:
np_a[:2:,:2]

array([[1, 2],
       [4, 5]])

In [31]:
np_a[0,:]

array([1, 2, 3])

##  useful functions

In [32]:
np.sum(np_a) #sum คือรวมเลข

21

In [33]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
np.sum(np_a,axis=0) #ค่าตั้งบวกกัน axis=0 รวมเลขในแต่ละแถว

array([5, 7, 9])

In [35]:
np.sum(np_a,axis=1) #ค่านอนบวกกัน axis=1 รวมเลขในแต่ละหลัก

array([ 6, 15])

In [36]:
np.mean(np_a)

3.5

In [38]:
np.mean(np_a,axis=0) #หา mean ของ column 

array([2.5, 3.5, 4.5])

## วนลูปเอง

# summation

In [43]:
np_a.shape

(2, 3)

In [49]:
sum_all = 0

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all = sum_all + np_a[row,col]
        print(f'we are at row={row},col={col} np_a[{row},{col}]={np_a[row,col]}  sum_all={sum_all}')
print(sum_all)

we are at row=0,col=0 np_a[0,0]=1  sum_all=1
we are at row=0,col=1 np_a[0,1]=2  sum_all=3
we are at row=0,col=2 np_a[0,2]=3  sum_all=6
we are at row=1,col=0 np_a[1,0]=4  sum_all=10
we are at row=1,col=1 np_a[1,1]=5  sum_all=15
we are at row=1,col=2 np_a[1,2]=6  sum_all=21
21


# np.sum(np_a,axis=0)

In [60]:
sum_all = np.zeros(np_a.shape[1])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[col] = sum_all[col] + np_a[row,col]
print(sum_all)



[5. 7. 9.]


Quiz กลุุ่ม

วนลูปหา 


*   np.sum(np_a,axis=1)
*   np.mean(np_a)
*   np.mean(np_a,axis=0)
*   np.mean(np_a,axis=1)



ข้อ 3 np.mean(np_a,axis=0)

In [65]:
## np.mean(np_a,axis=0)
mean_all = np.zeros(np_a.shape[1])
for row in range(np_a.shape[0]):
     for col in range(np_a.shape[1]):
          mean_all[col] = mean_all[col] + np_a[row,col]/np_a.shape[0]
print(mean_all)

[2.5 3.5 4.5]
